blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/Hankanman/Area-Occupancy-Detection
    about: Check our documentation before creating an issue
  - name: Discussions
    url: https://github.com/Hankanman/Area-Occupancy-Detection/discussions
    about: Ask questions and discuss with other users
