#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# Get only diffs for the custom_components folder
git diff main..dev -- custom_components/ > release_diff.txt

# Get commit messages, but only for commits that touched custom_components
git log main..dev --pretty=format:"%h%n%B%n---" -- custom_components/ > commit_messages.txt
