name: "Test"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
      - "dev"

jobs:
  test:
    name: "CI: Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements_test.txt

      - name: Run tests with pytest
        run: |
          pytest --cov=custom_components/area_occupancy --cov-report=xml --cov-report=term-missing

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
